apiVersion: v1
kind: ServiceAccount
metadata:
  name: chennai-flood-01
  namespace: opsera-chennai-flood-01-dev
  labels:
    app: chennai-flood-01
    tenant: opsera
    managed-by: opsera
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::PLACEHOLDER_AWS_ACCOUNT_ID:role/opsera-chennai-flood-01-irsa
