apiVersion: v1
kind: Service
metadata:
  name: chennai-flood-01
  namespace: opsera-chennai-flood-01-dev
  labels:
    app: chennai-flood-01
    tenant: opsera
    managed-by: opsera
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: chennai-flood-01
