apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chennai-flood-2000-dev
  namespace: argocd
  labels:
    app: chennai-flood-2000
    tenant: opsera
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-test-org/chennai-flood-watch.git
    targetRevision: main
    path: .opsera-chennai-flood-2000/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-chennai-flood-2000-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
