apiVersion: v1
kind: ConfigMap
metadata:
  name: chennai-flood-watch-config
  namespace: opsera-chennai-flood-watch-dev
  labels:
    app: chennai-flood-watch
    tenant: opsera
    managed-by: opsera-c2c
data:
  ENVIRONMENT: "dev"
  PORT: "8080"
  NODE_ENV: "production"
