apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chennai-flood-watch
  namespace: opsera-chennai-flood-watch-dev
  labels:
    app: chennai-flood-watch
    tenant: opsera
    managed-by: opsera-c2c
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: chennai-flood-watch-dev.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chennai-flood-watch
                port:
                  number: 80
