apiVersion: v1
kind: Service
metadata:
  name: chennai-flood-watch
  namespace: opsera-chennai-flood-watch-dev
  labels:
    app: chennai-flood-watch
    tenant: opsera
    managed-by: opsera-c2c
spec:
  type: ClusterIP
  selector:
    app: chennai-flood-watch
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
