apiVersion: v1
kind: ServiceAccount
metadata:
  name: chennai-flood-watch-sa
  namespace: opsera-chennai-flood-watch-dev
  labels:
    app: chennai-flood-watch
    tenant: opsera
    managed-by: opsera-c2c
