apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: chflood
  tenant: opsera
  managed-by: opsera

images:
- name: opsera/chflood
  newName: opsera/chflood
  newTag: latest
