apiVersion: v1
kind: ServiceAccount
metadata:
  name: chflood
  namespace: opsera-chflood-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::PLACEHOLDER_AWS_ACCOUNT_ID:role/chflood-role
  labels:
    app: chflood
    tenant: opsera
    managed-by: opsera
