apiVersion: v1
kind: Service
metadata:
  name: chflood
  namespace: opsera-chflood-dev
  labels:
    app: chflood
    tenant: opsera
    managed-by: opsera
spec:
  type: ClusterIP
  selector:
    app: chflood
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
