apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chennai-flood-2000-dev

resources:
  - ../../base

labels:
  - pairs:
      app: chennai-flood-2000
      tenant: opsera
      environment: dev
    includeSelectors: false

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
