apiVersion: v1
kind: ServiceAccount
metadata:
  name: chennai-flood-2000
  namespace: opsera-chennai-flood-2000-dev
  labels:
    app: chennai-flood-2000
    tenant: opsera
  annotations:
    eks.amazonaws.com/role-arn: ""  # IRSA role ARN (optional)
imagePullSecrets:
  - name: ecr-registry-secret
