apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-ch-flood-dev

resources:
  - ../../base

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: opsera-ch-flood-dev.agent.opsera.dev
    target:
      kind: Ingress
      name: ch-flood

labels:
  - pairs:
      environment: dev
    includeSelectors: false
