apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chflood-dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
      deployment-strategy: rolling
    includeSelectors: false

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/chflood
    newTag: 1b4ffe1-1771243345
