apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chflood-dev

resources:
- ../../base
- namespace.yaml
- ingress.yaml

patches:
- path: patch-replicas.yaml

commonLabels:
  environment: dev
  tenant: opsera
  opsera.io/environment: dev

images:
- name: opsera/chflood
  newName: opsera/chflood
  newTag: latest
