apiVersion: v1
kind: Namespace
metadata:
  name: opsera-chflood-dev
  labels:
    name: opsera-chflood-dev
    environment: dev
    tenant: opsera
    app: chflood
    managed-by: opsera
    opsera.io/environment: dev
    opsera.io/app: chflood
