apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chennai-flood-01-dev

resources:
  - ../../base

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest

labels:
  - pairs:
      environment: dev
    includeSelectors: false

replicas:
  - name: chennai-flood-01
    count: 2
