apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chennai-flood-01-dev

resources:
  - ../../base

images:
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/chennai-flood-01
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/chennai-flood-01
    newTag: 4dbea4e9-20260217065539

labels:
  - pairs:
      environment: dev
    includeSelectors: false

replicas:
  - name: chennai-flood-01
    count: 2
