apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chennai-flood-2025
  namespace: opsera-chennai-flood-2025-dev
  labels:
    app: chennai-flood-2025
    environment: dev
    tenant: opsera
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - opsera-chennai-flood-2025-dev.agent.opsera.dev
    secretName: chennai-flood-2025-tls
  rules:
  - host: opsera-chennai-flood-2025-dev.agent.opsera.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chennai-flood-2025
            port:
              number: 80
