apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chennai-flood-2025-dev

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - includeSelectors: false
    pairs:
      app: chennai-flood-2025
      tenant: opsera
      managed-by: argocd

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
