apiVersion: v1
kind: Service
metadata:
  name: chennai-flood-2025
  namespace: opsera-chennai-flood-2025-dev
  labels:
    app: chennai-flood-2025
    environment: dev
    tenant: opsera
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: chennai-flood-2025
    environment: dev
