apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chennai-flood-2025-dev

resources:
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      environment: dev

replicas:
  - name: chennai-flood-2025
    count: 2

patches:
  - target:
      kind: Ingress
      name: chennai-flood-2025
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: opsera-chennai-flood-2025-dev.agent.opsera.dev
      - op: replace
        path: /spec/rules/0/host
        value: opsera-chennai-flood-2025-dev.agent.opsera.dev
